### ISSUE TITLE
Do not use reserved configuration namespace in third party starter

### ISSUE THREAD

**Issue by snicoll** [hazelcast/hazelcast-jet-contrib#62]
Please [do not use](https://github.com/hazelcast/hazelcast-jet-contrib/blob/9a2bb1b6e22a92d11b7823154fbab0133d21b410/hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetProperties.java#L26)  the `spring.*` configuration namespace in a third party starter.

See [the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-configuration-keys) for more details.

**Comment by eminn** [comment]
Thanks for the feedback @snicoll
